"""
exercise_database.py
Master exercise database organised by joint action.

This is the primary source of exercise data going forward.
EXERCISE_LIBRARY in data.py remains the runtime system for now.

Structure per exercise:
    name            — str
    video           — str or None
    rationale       — str
    variations      — list[str]
    synergist       — list[str] (raw strings, not normalised)
    traits          — dict (joint_action, secondary_actions, tertiary_actions, adaptation)
    equipment       — None (not yet assigned)
    eccentric_heavy — None (not yet assigned)
    weeks           — None (not yet assigned)
"""

EXERCISE_DATABASE = {
    "hip_extension": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Reverse Hyperextension",
            "video": "https://www.youtube.com/watch?v=jUZkw1q90cs",
            "rationale": "2nd class lever produces high force with trunk stabilised. Open Chain. Moderate RoM",
            "variations": ["Bent knee", "Bent to straight", "Straight", "Unilateral", "Loaded"],
            "synergist": ["Lumbar Extension"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hip Thrust Partial Range ISO",
            "video": None,
            "rationale": "Closed chain. High force. Controlled short RoM",
            "variations": ["Depth", "Tempo"],
            "synergist": ["Lumbar Extension", "Knee Flexors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Romanian Deadlift",
            "video": None,
            "rationale": "Short lever, high force, large RoM targets isometric muscle action and tendon strain, posterior chain dominant. Closed Chain",
            "variations": ["Equipment"],
            "synergist": ["Lumbar Extension", "Knee Flexors", "Posterior Shoulder"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Razorcurl",
            "video": "https://youtu.be/R8MvuVmFcOE",
            "rationale": "Deep range of motion activates adductor magnus. Open Chain",
            "variations": ["Depth", "Anchor"],
            "synergist": ["Knee Flexors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Reverse Lunge",
            "video": None,
            "rationale": "Deep range of motion and movement vector increase hip extension moment. Open Chain",
            "variations": ["Equipment", "Set Up (Heel Floating)", "Depth", "Balance at the end", "Sliding"],
            "synergist": ["Plantar Flexors (heel floating)"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction"],
                "tertiary_actions": ["hip_abduction"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "90/90 Glute Bridge",
            "video": "https://www.youtube.com/watch?v=ClFYr03yUUU",
            "rationale": "Moderate RoM targets hip extensors. Closed Chain",
            "variations": ["Hold", "Reps", "Load"],
            "synergist": ["Lumbar Extension"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction", "hip_abduction"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "High Step Up",
            "video": None,
            "rationale": "Moderate RoM recruits hip extensors. Open Chain",
            "variations": ["Equipment", "Height", "Balance at the end"],
            "synergist": ["Trunk", "Plantar Flexors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["knee_extension"],
                "tertiary_actions": ["hip_adduction", "hip_abduction"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Good Morning",
            "video": None,
            "rationale": "Long lever, high hip extension torque, large range of motion, posterior chain dominant. Closed Chain. Isometric action of muscle targets tendon strain",
            "variations": ["Depth", "Long Lever (Overhead)"],
            "synergist": ["Lumbar Extension", "Knee Flexors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hyperextension",
            "video": "https://youtu.be/RgJuztpRkio",
            "rationale": "Segmental dynamic lumbar extension driven by the hip extensors. Open chain",
            "variations": [],
            "synergist": ["Knee Flexors", "Lumbar Extension"],
            "traits": {
                "joint_action": "hip_extension",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Plantar Flexed Hamstring Bridge",
            "video": "https://youtu.be/yZ-a0g_7y0Q",
            "rationale": "Angle of the hips targets adductor magnus, whilst the plantar flexed set up engages soleus and knee flexors which reduces muscle slack in the hamstrings",
            "variations": [],
            "synergist": ["Lumbar Extensors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["knee_flexion"],
                "tertiary_actions": ["plantar_flexion"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Single Leg Good Morning",
            "video": "https://www.youtube.com/watch?v=YDUdKj1qK5Q",
            "rationale": "Unilateral increase torque on stance hip extensors to stabilise, Posterior chain dominant. Closed Chain",
            "variations": ["Depth", "Equipment", "Auxiliary thoracic movements"],
            "synergist": ["Knee Flexors", "Plantar Flexors", "Trunk"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_abduction"],
                "tertiary_actions": ["hip_internal_rotation", "hip_external_rotation"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Motor Control ─────────────────────────────────────────────
        {
            "name": "SL Hip Thrust",
            "video": "https://www.youtube.com/watch?v=cUz04QPvPT0",
            "rationale": "Deep range of motion targets glute max, Abductors stabilsie hip. Closed Chain",
            "variations": [],
            "synergist": ["Lumbar Extension", "Contralateral Obliques"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction", "hip_abduction"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "SL Bridge Variations",
            "video": None,
            "rationale": "Stance generates more extension force as free limb extends. Closed Chain",
            "variations": ["Contralateral Leg: Raises, Abductions, ER/IR rotations"],
            "synergist": ["Lumbar Extension"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_flexion"],
                "tertiary_actions": ["hip_adduction", "hip_abduction"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Arabesque Rotations",
            "video": "https://www.youtube.com/watch?v=MbHKxxzzuDo",
            "rationale": "Unilateral increase torque on stance hip extensors to stabilise, Posterior chain dominant. Closed Chain",
            "variations": ["Depth", "Equipment", "Auxiliary thoracic movements"],
            "synergist": ["Knee Flexors", "Plantar Flexors", "Trunk"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_abduction"],
                "tertiary_actions": ["hip_internal_rotation", "hip_external_rotation"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Wall Bridge Circles",
            "video": "https://www.youtube.com/watch?v=wv-3O9Iajuk",
            "rationale": "Driver of the free limb creates greater 3D moments on the locked in hip. Closed Chain",
            "variations": [],
            "synergist": ["Lumbar Extension", "Plantar Flexion"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_adduction", "hip_abduction"],
                "tertiary_actions": ["hip_internal_rotation", "hip_external_rotation"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "hip_adduction": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Seated Adductor Machine",
            "video": None,
            "rationale": "Closed Chain. High Force. Low techncial. Small range of motion",
            "variations": ["Knee angles"],
            "synergist": [],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B1: Primary Movement = Extension, section = hip adduction
            # joint_action follows Primary Movement column
            "name": "Sumo Squat",
            "video": None,
            "rationale": "Force & form closure of SIJ. Closed Chain",
            "variations": ["Equipment", "Tempo"],
            "synergist": ["Trunk to stabilise"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_abduction", "hip_adduction"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Isometric Adduction Squeeze",
            "video": None,
            "rationale": "Closed chain. Short RoM. High MU recruitment",
            "variations": ["Knee angles"],
            "synergist": [],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hip Adduction Cable Catches",
            "video": "https://youtu.be/8585jmSd-tg",
            "rationale": "Taregts high slack properties of adductors via a high load eccentric action",
            "variations": ["Cable/Band", "Range"],
            "synergist": [],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Bent Knee Copenhagen",
            "video": None,
            "rationale": "Class 2 lever places high levels of adduction force. Closed Chain",
            "variations": ["Dynamic (dips, T-Spine rotation)", "Angle"],
            "synergist": ["Lateral Trunk Flexors"],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Straight Knee Copenhagen",
            "video": None,
            "rationale": "Progression on bent knee. Closed Chain",
            "variations": ["Dynamic (dips, T-Spine rotation)", "Angle"],
            "synergist": ["Lateral Trunk Flexors"],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B1: Primary Movement = Extension, section = hip adduction
            # joint_action follows Primary Movement column
            "name": "Ipsilateral Loaded Single Leg",
            "video": None,
            "rationale": "Load position creates greater load through the adductor complex to stabilise",
            "variations": ["Weight Position", "Exercise (Split Squat, Bulgarian, Lunge, Step up)"],
            "synergist": ["Knee Extensors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_abduction", "hip_adduction"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Band/Cable Standing ADD",
            "video": None,
            "rationale": "Open chain, greater eccentric emhpasis in stance",
            "variations": ["Range"],
            "synergist": ["Trunk Stability"],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Lateral Adductor Slide",
            "video": "https://www.youtube.com/watch?v=BP8-ZUcHS6c",
            "rationale": "Closed Chain concetric dominant",
            "variations": ["Band loaded", "Surface"],
            "synergist": ["Contralateral ABD stabilising"],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B1: Primary Movement = Extension, section = hip adduction
            # joint_action follows Primary Movement column
            "name": "Lateral Step Up/Lunge",
            "video": None,
            "rationale": "Single limb force & form closure of SIJ. Oipen Chain",
            "variations": ["Height", "Range"],
            "synergist": ["Knee Extensors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_abduction", "hip_adduction"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Motor Control ─────────────────────────────────────────────
        {
            # B2: Primary Movement = ABD & ADD, section = hip adduction
            # joint_action follows section header; other action to secondary
            "name": "Side Lying Knee to Knee",
            "video": "https://www.youtube.com/watch?v=L_02NrInLS4",
            "rationale": "Replicates LPHC motor control during gait. Closed Chain",
            "variations": [],
            "synergist": ["Anterior trunk to stabilise"],
            "traits": {
                "joint_action": "hip_adduction",
                "secondary_actions": ["hip_abduction"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B2: Primary Movement = ABD & ADD, section = hip adduction
            # joint_action follows section header; other action to secondary
            "name": "Wall Bridge Rolls",
            "video": "https://www.youtube.com/watch?v=RHHzP43w-do",
            "rationale": "Replicates LPHC motor control during gait. Closed Chain",
            "variations": [],
            "synergist": ["Lumbar Extension"],
            "traits": {
                "joint_action": "hip_adduction",
                "secondary_actions": ["hip_abduction"],
                "tertiary_actions": ["hip_extension"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Stability Ball Kneeling Balance",
            "video": None,
            "rationale": "Open Chain unstable control using Adductors to cocontract to stabilise",
            "variations": ["Time", "Movement (Squat, Lateral Shift, Perception)"],
            "synergist": ["Trunk Stability"],
            "traits": {
                "joint_action": "hip_adduction",
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "hip_abduction": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Seated Abductor Machine",
            "video": None,
            "rationale": "Closed Chain. High Force. Low techncial. Small range of motion",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "hip_abduction",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Plate Loaded Clam",
            "video": "https://youtu.be/PfeUXjlDz-A",
            "rationale": "Heavy load, short RoM recruits Gmed. Open Chain",
            "variations": ["Hip/knee angle"],
            "synergist": [],
            "traits": {
                "joint_action": "hip_abduction",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Side Lying Wall Slide",
            "video": "https://www.youtube.com/watch?v=26Z-OinQCD0",
            "rationale": "Isolates Abductors through high voluntary force, short range of motion recruits Gmed. Closed Chain",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "hip_abduction",
                "secondary_actions": ["hip_extension"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hip Hitch",
            "video": "https://www.youtube.com/watch?v=vzPjKJ8FWF4",
            "rationale": "Isolated standing hip abduction motor control. Open Chain",
            "variations": ["Load Position"],
            "synergist": ["Contralateral Oblique", "Ankle Evertors"],
            "traits": {
                "joint_action": "hip_abduction",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Band/Cable Standing ABD",
            "video": "https://www.youtube.com/watch?v=vSqhrbzZb7A",
            "rationale": "Open chain, greater eccentric emhpasis in stance",
            "variations": [],
            "synergist": ["Trunk Stability"],
            "traits": {
                "joint_action": "hip_abduction",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Side Lying Leg Raises",
            "video": "https://www.youtube.com/watch?v=zrZuHi7EeWs",
            "rationale": "Class 2 lever in the hip drives greater MU recruitment",
            "variations": [],
            "synergist": ["Lateral Trunk"],
            "traits": {
                "joint_action": "hip_abduction",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B1: Primary Movement = Extension, section = hip abduction
            # joint_action follows Primary Movement column
            "name": "Contralateral Loaded Single Leg",
            "video": None,
            "rationale": "Load position creates greater load through the abductor complex to stabilise",
            "variations": ["Weight Position", "Exercise (Split Squat, Bulgarian, Lunge, Step up)"],
            "synergist": ["Knee Extensors"],
            "traits": {
                "joint_action": "hip_extension",
                "secondary_actions": ["hip_abduction", "hip_adduction"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Motor Control ─────────────────────────────────────────────
        {
            # B2: Primary Movement = ABD & ADD, section = hip abduction
            # joint_action follows section header; other action to secondary
            "name": "Side Lying Knee to Knee",
            "video": None,
            "rationale": "Replicates LPHC motor control during gait. Closed Chain",
            "variations": [],
            "synergist": ["Lateral Trunk"],
            "traits": {
                "joint_action": "hip_abduction",
                "secondary_actions": ["hip_adduction"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B2: Primary Movement = ABD & ADD, section = hip abduction
            # joint_action follows section header; other action to secondary
            "name": "Wall Bridge Rolls",
            "video": None,
            "rationale": "Replicates LPHC motor control during gait. Closed Chain",
            "variations": [],
            "synergist": ["Lumbar Extension"],
            "traits": {
                "joint_action": "hip_abduction",
                "secondary_actions": ["hip_adduction"],
                "tertiary_actions": ["hip_extension"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Clams",
            "video": None,
            "rationale": "Low load and RoM helps stimulate specific MU recruitment with compensatory patterns overworking",
            "variations": [],
            "synergist": ["Lateral Trunk"],
            "traits": {
                "joint_action": "hip_abduction",
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Crab Walks",
            "video": None,
            "rationale": "Low load and RoM helps stimulate specific MU recruitment with compensatory patterns overworking",
            "variations": [],
            "synergist": ["Contralateral triple extensors"],
            "traits": {
                "joint_action": "hip_abduction",
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "hip_flexion": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Supine KB Bent Leg Lower",
            "video": "https://www.youtube.com/watch?v=OmMoGenisNA",
            "rationale": "Eccentric contraction of the hip flexors through range and under control. Open Chain distal driver",
            "variations": [],
            "synergist": ["Anterior Trunk"],
            "traits": {
                "joint_action": "hip_flexion",
                "secondary_actions": ["knee_extension"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Single Supine Roll Backs",
            "video": None,
            "rationale": "Eccentric contraction of the hip flexors through range and under control. Open Chain proximal driver",
            "variations": [],
            "synergist": ["Anterior Trunk"],
            "traits": {
                "joint_action": "hip_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Single Leg Feet Raised Partner Isometric",
            "video": "https://www.youtube.com/shorts/GBUPZxczJAk",
            "rationale": "Isometric action of hip flexors in neutral creates tendon strain",
            "variations": [],
            "synergist": ["Anterior Trunk", "Anterior Shoulder", "Elbow Extensors"],
            "traits": {
                "joint_action": "hip_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B5: Dual adaptation value — stored as list
            "name": "Standing SL Knee Drive",
            "video": "https://youtu.be/STgug7ArYzo",
            "rationale": "Targets the muscle slack properties of the hip flexors through explosive conenctric and controlled eccentric action whilst locking in the stance leg. Open Chain.",
            "variations": [],
            "synergist": ["Contralateral Limb Extensors", "Trunk Stabilisers"],
            "traits": {
                "joint_action": "hip_flexion",
                "adaptation": ["fmax", "rfd"],
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Supine Mini Band Hip Flexion",
            "video": "https://www.youtube.com/watch?v=tD_05CZZtqU",
            "rationale": "Active flexion of the hip. Open Chain",
            "variations": [],
            "synergist": ["Anterior Trunk"],
            "traits": {
                "joint_action": "hip_flexion",
                "secondary_actions": ["hip_extension"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Supine 90/90 Mini Band Leg Extension",
            "video": "https://www.youtube.com/watch?v=EfgdPQmnIg0",
            "rationale": "Passive isometric hold of the hip flexors as the contralteral leg is extended. Close Chain",
            "variations": [],
            "synergist": ["Anterior Trunk"],
            "traits": {
                "joint_action": "hip_flexion",
                "secondary_actions": ["hip_extension"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Seated SL Leg Raises (over object)",
            "video": "https://www.youtube.com/watch?v=LUZdadnRWBU",
            "rationale": "Targets more medial and lateral fibres at inner range whilst requireing the lumbar to be anchored. Open Chain",
            "variations": ["Object Height"],
            "synergist": ["Trunk Stability"],
            "traits": {
                "joint_action": "hip_flexion",
                "secondary_actions": ["hip_adduction", "hip_abduction"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Supine Straight Leg Raise",
            "video": "https://www.youtube.com/watch?v=oV99_zvhl_A&t=15s",
            "rationale": "Long lever hip flexion. Open Chain",
            "variations": [],
            "synergist": ["Anterior Trunk"],
            "traits": {
                "joint_action": "hip_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hanging Leg Raises",
            "video": None,
            "rationale": "Class 2 lever distal driver",
            "variations": [],
            "synergist": ["Anterior Trunk"],
            "traits": {
                "joint_action": "hip_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Motor Control ─────────────────────────────────────────────
        {
            "name": "Seated Knee Elevations",
            "video": None,
            "rationale": "Resist comepnsatory movements to flex hip. Open Chain",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "hip_flexion",
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B6: "Hip Extensors" normalised to hip_extension
            "name": "Stability Ball Plank Leg Raises Off Ball",
            "video": None,
            "rationale": "Stabilise through contralateral limb as leg is raised off the unstable ball. Closed Chain",
            "variations": [],
            "synergist": ["Anterior Trunk", "Anterior Shoulder"],
            "traits": {
                "joint_action": "hip_flexion",
                "secondary_actions": ["hip_extension"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Stability Ball Single Leg Jacknife",
            "video": None,
            "rationale": "Stabilise through the working leg as it moves through flexion and extension. Closed chain",
            "variations": [],
            "synergist": ["Anterior Trunk", "Anterior Shoulder"],
            "traits": {
                "joint_action": "hip_flexion",
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "knee_extension": [
        # ── LME ───────────────────────────────────────────────────────
        # Note: this is an accessory-focused subset. Primary Fmax
        # movements (e.g. back squat, leg press) are not included here.
        {
            "name": "Spanish Squat",
            "video": "https://www.youtube.com/watch?v=jsMMo9hHNVU",
            "rationale": "Isolates knee extensors whilst challenging eccentrically motor contorl when using band. Short range of motion targets VMO. Closed Chain",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "knee_extension",
                "secondary_actions": ["hip_extension"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hack Squat",
            "video": None,
            "rationale": "Axial loaded with knee extension bias. Closed Chain",
            "variations": [],
            "synergist": ["Trunk Stabilisation"],
            "traits": {
                "joint_action": "knee_extension",
                "secondary_actions": ["plantar_flexion"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Seated Knee Extension",
            "video": None,
            "rationale": "Open chain fixed machine",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "knee_extension",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Forward Step Down",
            "video": "https://www.youtube.com/watch?v=yzphcRAdjg4",
            "rationale": "Places greater load through the plantar flexors to control knee flexion during eccentric phase",
            "variations": ["Direction of step down"],
            "synergist": [],
            "traits": {
                "joint_action": "knee_extension",
                "secondary_actions": ["plantar_flexion"],
                "tertiary_actions": ["hip_extension"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Sit to Stand",
            "video": "https://www.youtube.com/watch?v=uJ4eA2wUXdw",
            "rationale": "Acts as a class 3 lever place greater strain on the quad to control eccentric action. Greater contribution from the hip extensors",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "knee_extension",
                "secondary_actions": ["hip_extension"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Motor Control ─────────────────────────────────────────────
        {
            "name": "TKE",
            "video": "https://www.youtube.com/watch?v=RUhYq-n_2Po",
            "rationale": "Isolated action to engage knee extensors",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "knee_extension",
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Reverse Nordics",
            "video": "https://www.youtube.com/watch?v=x2K8uH7dcqg",
            "rationale": "Slow eccentric action through large knee RoM",
            "variations": [],
            "synergist": ["Trunk Stabilisation"],
            "traits": {
                "joint_action": "knee_extension",
                "secondary_actions": ["hip_extension"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Tantrums",
            "video": None,
            "rationale": "Fast contractions elicit great MU recruitment and neural drive",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "knee_extension",
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "knee_flexion": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Nordic",
            "video": None,
            "rationale": "Suprmaximal eccentric contraction of the knee flexors. Open Chain",
            "variations": [],
            "synergist": ["Hip Extensors"],
            "traits": {
                "joint_action": "knee_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Full Razor Curl",
            "video": "https://www.youtube.com/watch?v=HuPyYj5F5Es",
            "rationale": "Suprmaximal eccentric contraction of the knee flexors and hip extensors. Open Chain great length tension relationship",
            "variations": [],
            "synergist": ["Hip Extensors"],
            "traits": {
                "joint_action": "knee_flexion",
                "secondary_actions": ["hip_flexion"],
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Eccentric Slide/Roll Out",
            "video": None,
            "rationale": "Controlled eccentric contraction of knee flexors. Closed Chain",
            "variations": [],
            "synergist": ["Hip Extensors", "Lumbar Extensors"],
            "traits": {
                "joint_action": "knee_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "2 Down 1 Up Hamstring Machine",
            "video": None,
            "rationale": "Suprmaximal eccentric contraction of the knee flexors. Closed Chain",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "knee_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Hamstring Curls",
            "video": None,
            "rationale": "Lots of variation to challenge knee flexors to suit programme context",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "knee_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Foam Roller Hamstring Bridge",
            "video": None,
            "rationale": "The plantar flexed set up engages soleus and knee flexors which reduces musclee slack in the hamstrings increasing MU recruitment. Closed Chain",
            "variations": ["Oscillations"],
            "synergist": ["Lumbar Extension"],
            "traits": {
                "joint_action": "knee_flexion",
                "secondary_actions": ["hip_extension"],
                "tertiary_actions": ["plantar_flexion"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Prone Band Isometric Hamstring Curl",
            "video": None,
            "rationale": "Elasticity of the band creates a constant resistance",
            "variations": ["Knee angle"],
            "synergist": [],
            "traits": {
                "joint_action": "knee_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            # B7: "Ankle DF & PF" normalised to dorsi_flexion + plantar_flexion
            "name": "Hamstring Bridge Ankle Pump",
            "video": None,
            "rationale": "Dynamic movement of the ankle in the sagital plane creates increased load through the knee flexors due to change in length tension. Closed Chain",
            "variations": [],
            "synergist": ["Lumbar Extensors"],
            "traits": {
                "joint_action": "knee_flexion",
                "secondary_actions": ["hip_extension"],
                "tertiary_actions": ["dorsi_flexion", "plantar_flexion"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Motor Control / RFD ───────────────────────────────────────
        {
            # B8: "Motor Control/ RFD" stored as list
            # B9: Also appears in knee_extension as motor_control
            "name": "Tantrums",
            "video": None,
            "rationale": "Explosive high velocity knee flexors targetted to postively effect neural drive. Open Chain",
            "variations": ["Knee range of motion"],
            "synergist": [],
            "traits": {
                "joint_action": "knee_flexion",
                "adaptation": ["motor_control", "rfd"],
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hamstring Switch March",
            "video": "https://www.youtube.com/watch?v=bWYYyUjI_cc",
            "rationale": "Explosive action targets high slack properties of the hamstrings",
            "variations": [],
            "synergist": ["Hip Extension", "Lumbar Extension"],
            "traits": {
                "joint_action": "knee_flexion",
                "adaptation": "rfd",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],
    "foot": [
        {
            "name": "Foot Bridge",
            "video": "https://youtu.be/68EvjMGABWo",
            "rationale": "Absense of ground contact with the medial and lateral arch drives stiffness through the midfoot and activation of FHL",
            "variations": ["Eye", "Head", "T-Spine Rotations", "Reaches", "Squats", "Arabesques", "Compass Balance", "Heavy axial load"],
            "synergist": ["Plantar Flexors"],
            "traits": {
                "joint_action": "foot",
                "primary_structure": "medial_lateral_arch",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Banded Toe Hold Arabesque",
            "video": "https://youtu.be/XVy01Bn-rpw",
            "rationale": "Active flexion of the FHL to pin band down",
            "variations": [],
            "synergist": ["Plantar Flexors"],
            "traits": {
                "joint_action": "foot",
                "primary_structure": "fhl",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Low Amplitude Pogos",
            "video": "https://www.youtube.com/watch?v=J6UvXryVva4",
            "rationale": "Fast SSC. Short ground contacts generates stiffness in the three forefoot arches",
            "variations": ["Travel", "Direction"],
            "synergist": [],
            "traits": {
                "joint_action": "foot",
                "primary_structure": "forefoot",
                "secondary_actions": ["plantar_flexion"],
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Big Toe Flexions with TB",
            "video": "https://youtu.be/Aj6vdyaI6ig",
            "rationale": "Increase FHL strength",
            "variations": ["Increase TB colour", "Use mini bands", "Add in other exercises (arabesque, squat, wall drive)"],
            "synergist": [],
            "traits": {
                "joint_action": "foot",
                "primary_structure": "fhl",
                "secondary_actions": ["plantar_flexion"],
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Towel Scrunches",
            "video": "https://www.youtube.com/watch?v=XEJYq1HBtHY",
            "rationale": "Concentric action of the toe extensors",
            "variations": ["Various weight towels (paper/cotton/normal)"],
            "synergist": [],
            "traits": {
                "joint_action": "foot",
                "primary_structure": ["fhl", "fdl"],
                "secondary_actions": ["plantar_flexion"],
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Alternating Big Toe and Smaller Toe Extensions",
            "video": "https://www.youtube.com/watch?v=9koRqQhN8QE",
            "rationale": "dissociation of the FHL and FDL",
            "variations": ["Band"],
            "synergist": [],
            "traits": {
                "joint_action": "foot",
                "primary_structure": ["fhl", "fdl"],
                "secondary_actions": ["plantar_flexion"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Wedge Calf Raise",
            "video": "https://www.youtube.com/watch?v=vWMmkD-lAsY",
            "rationale": "Wedge flexes first ray to create greater range of motion",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "foot",
                "primary_structure": "fhl",
                "secondary_actions": ["plantar_flexion"],
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "inversion": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Cable Inversion",
            "video": None,
            "rationale": "High Load short fast actions targets tendon slack",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "inversion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Isometric Inversion",
            "video": None,
            "rationale": "Low force potential targets tendon health",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "inversion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Band Inversion",
            "video": None,
            "rationale": "Elasticity of bands targets higher MU recruitment",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "inversion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "eversion": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Cable Eversion",
            "video": None,
            "rationale": "High Load short fast actions targets tendon slack",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "eversion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Isometric Eversion",
            "video": None,
            "rationale": "Low force potential targets tendon health",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "eversion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Band Eversion",
            "video": None,
            "rationale": "Elasticity of bands targets higehr MU recruitment",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "eversion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Ankle Rolls on Step",
            "video": None,
            "rationale": "Eccentric and concentric control of the peroneals to strengthen the muscles in a adverse position",
            "variations": ["On a wedge", "+ weight"],
            "synergist": [],
            "traits": {
                "joint_action": "eversion",
                "secondary_actions": ["plantar_flexion"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Eccentric Ankle Roll Walks",
            "video": None,
            "rationale": "Eccentric and concentric control of the peroneals to strengthen the muscles in a adverse position",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "eversion",
                "secondary_actions": ["plantar_flexion"],
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Motor Control ─────────────────────────────────────────────
        {
            "name": "Unstable Surface Balance",
            "video": None,
            "rationale": "Proprioception",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "eversion",
                "secondary_actions": ["inversion"],
                "adaptation": "motor_control",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "dorsi_flexion": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Loaded Dorsiflexion",
            "video": None,
            "rationale": "Short RoM under load targets tendon slack",
            "variations": ["Cable", "KB"],
            "synergist": ["Evertors"],
            "traits": {
                "joint_action": "dorsi_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Band/Cable DF Isometrics",
            "video": None,
            "rationale": "Targets high MU recruitment in short RoM",
            "variations": [],
            "synergist": ["Evertors"],
            "traits": {
                "joint_action": "dorsi_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Tib Ant Raises",
            "video": None,
            "rationale": "Short RoM - long lever creates greater moment arm",
            "variations": [],
            "synergist": ["Evertors"],
            "traits": {
                "joint_action": "dorsi_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Heel Walk",
            "video": None,
            "rationale": "Short isometric RoM",
            "variations": [],
            "synergist": ["Evertors"],
            "traits": {
                "joint_action": "dorsi_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "plantar_flexion": [
        # ── Fmax ──────────────────────────────────────────────────────
        {
            "name": "Isometric Standing",
            "video": None,
            "rationale": "High pennation and PSCA of soleus requires it to have high force over short ranges.",
            "variations": ["Straight Knee", "Bent Knee"],
            "synergist": ["Trunk Stabilisation", "Hip Extensors", "Knee Extensors"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Isometric Leg Press",
            "video": None,
            "rationale": "",
            "variations": ["Straight Knee", "Bent Knee"],
            "synergist": ["Hip Extensors", "Knee Extensors"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Isometric Seated Calf Machine",
            "video": None,
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Eccentric Standing",
            "video": None,
            "rationale": "High-moderate tendon slack is targeted through supramaximal eccentric actions",
            "variations": ["Straight Knee", "Bent Knee"],
            "synergist": ["Trunk Stabilisation", "Hip Extensors", "Knee Extensors"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Eccentric Leg Press",
            "video": None,
            "rationale": "",
            "variations": ["Straight Knee", "Bent Knee"],
            "synergist": ["Hip Extensors", "Knee Extensors"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Eccentric Seated Calf Machine",
            "video": None,
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "fmax",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── LME ───────────────────────────────────────────────────────
        {
            "name": "Standing",
            "video": None,
            "rationale": "Recruits all plantar flexors",
            "variations": ["Use a stability ball, lean against the wall at a 45 degree angle to increase moment arm"],
            "synergist": ["Hip Extensors"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Bent Knee",
            "video": None,
            "rationale": "Soleus biased. Dissassociation of ankle to stable knee",
            "variations": [],
            "synergist": ["Knee Extensors"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Plie",
            "video": None,
            "rationale": "Soleus biased. Dissassociation of ankle to stable knee. Angle also targets FHL",
            "variations": [],
            "synergist": ["Knee Extensors"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Seated Calf Raise",
            "video": None,
            "rationale": "Soleus biased. Lower motor control and complexity. Closed Chain",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Heel Floating Hold",
            "video": "https://www.youtube.com/watch?v=VGbgrMdFfAk",
            "rationale": "Isometric action that targets greater concontractions between instrinisc foot muscles and plantar flexors",
            "variations": [],
            "synergist": ["Knee Extensors", "Hip Extensors", "Foot"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Crouched Calf Walk",
            "video": None,
            "rationale": "Dynamic cyclicle action",
            "variations": ["Direction"],
            "synergist": ["Knee Extensors", "Hip Extensors", "Foot"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "lme",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── Tendon ────────────────────────────────────────────────────
        {
            "name": "Prowler Push",
            "video": None,
            "rationale": "Large moment arm creates high load",
            "variations": [],
            "synergist": ["Trunk Stabilisation"],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["knee_extension"],
                "tertiary_actions": ["hip_extension"],
                "adaptation": "tendon",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Sled Crawl",
            "video": None,
            "rationale": "Large moment arm creates high load. Big redcruitment of FHL",
            "variations": [],
            "synergist": ["Trunk Stabilisation"],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["knee_extension"],
                "tertiary_actions": ["hip_extension"],
                "adaptation": "tendon",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Bent Knee Pogo",
            "video": None,
            "rationale": "Knee flexion generates greater rigidity and force throughout body resulting in greater tendon loading",
            "variations": ["Travel", "Direction"],
            "synergist": ["Knee Extensors", "Hip Extensors", "Foot", "Eversion"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "tendon",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Drop Jump",
            "video": None,
            "rationale": "Explosive Fast SSC action",
            "variations": ["Height", "Box to box", "Direction"],
            "synergist": ["Foot", "Eversion"],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["knee_extension"],
                "adaptation": "tendon",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Single Leg Plate Hops",
            "video": "https://www.youtube.com/watch?v=Y_r5xXO5R4Q",
            "rationale": "Slow SSC - backwards vector of the exercise creates greater moment arm aroud achillies",
            "variations": ["Direction"],
            "synergist": ["Hip Extensors", "Foot", "Eversion"],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["knee_extension"],
                "adaptation": "tendon",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },

        # ── RFD ───────────────────────────────────────────────────────
        {
            "name": "Pogos High Amplitude",
            "video": None,
            "rationale": "Slow SSC due to high amplitude places greater emphasis on contractile components",
            "variations": ["Travel", "Direction"],
            "synergist": ["Knee Extensors", "Hip Extensors", "Foot", "Eversion"],
            "traits": {
                "joint_action": "plantar_flexion",
                "adaptation": "rfd",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Tuck Jumps",
            "video": None,
            "rationale": "Moderate SSC due to high amplitude places greater emphasis on contractile components",
            "variations": ["Travel", "Direction"],
            "synergist": ["Hip Extensors", "Eversion"],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["knee_extension"],
                "adaptation": "rfd",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Ankling",
            "video": None,
            "rationale": "Pre flex of dorsi flexors allows for greater force application",
            "variations": ["Travel", "Direction"],
            "synergist": ["Hip Extensors", "Knee Extensors", "Eversion"],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["dorsi_flexion"],
                "adaptation": "rfd",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Hops",
            "video": None,
            "rationale": "Moderate SSC drives force projection through triple extensors",
            "variations": ["Travel", "Direction"],
            "synergist": [],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["knee_extension"],
                "tertiary_actions": ["hip_extension"],
                "adaptation": "rfd",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Depth Jumps",
            "video": None,
            "rationale": "Slow SSC due to high GRF places greater emphasis on contractile components",
            "variations": ["Height", "Box to Box"],
            "synergist": ["Trunk Stabilisers", "Eversion"],
            "traits": {
                "joint_action": "plantar_flexion",
                "secondary_actions": ["knee_extension"],
                "tertiary_actions": ["hip_extension"],
                "adaptation": "rfd",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    # ═══════════════════════════════════════════════════════════════════
    # UPPER BODY
    # ═══════════════════════════════════════════════════════════════════

    "overhead": [
        {
            "name": "Piked Handstand Hold",
            "video": "https://youtube.com/shorts/Inq-rEYpH6I",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "overhead",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Handstand Hold",
            "video": "https://youtube.com/shorts/y5I7-QHXrF8",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "overhead",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Handstand Shrugs",
            "video": "https://youtube.com/shorts/NdySu5Nq324",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "overhead",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Piked Handstand Taps",
            "video": "https://youtube.com/shorts/l0pYjPTFeeE",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "overhead",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Open Handstand Hold",
            "video": "https://youtube.com/shorts/r9fAdeW3eNw",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "overhead",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Handstand Wall Walks",
            "video": "https://youtube.com/shorts/10tWITsByJQ",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "overhead",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "upper_push": [
        {
            "name": "Power Push Ups",
            "video": "https://www.youtube.com/shorts/VAeuSO-aTZA",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_push",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Piked Push Up",
            "video": "https://www.youtube.com/shorts/kqPtCQZUj9c",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_push",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Kneeling Front Raise",
            "video": "https://www.youtube.com/shorts/MzsZeW5B700",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_push",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Press Ups",
            "video": "https://www.youtube.com/shorts/Hx8FyIJNzgg",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_push",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Kneeling Front Raise w/ Band",
            "video": "https://youtube.com/shorts/wEeUFXjQaIQ",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_push",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Kneeling DB Press",
            "video": "https://youtube.com/shorts/oImnoWBhpdA",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_push",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "upper_pull": [
        {
            "name": "Pull Up",
            "video": "https://youtube.com/shorts/oOxJD6MBs5Y",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_pull",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Chest Supported DB Row",
            "video": "https://youtube.com/shorts/JdHIuL93qV8",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_pull",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Chest Supported Front Raise",
            "video": "https://youtube.com/shorts/IrEKVkC9Q-c",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "upper_pull",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],

    "trunk": [
        # Note: these are upper-body trunk exercises (posterior chain / arch work).
        # Distinct from the hip_extension exercises and from the brace section
        # trunk stiffness exercises already in EXERCISE_LIBRARY.
        {
            "name": "Arch Rocks",
            "video": "https://www.youtube.com/shorts/VJtsVDRDd9I",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "trunk",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Arch Lifts",
            "video": "https://www.youtube.com/shorts/xItnoRXb3FU",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "trunk",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "IWTs",
            "video": "https://www.youtube.com/shorts/0pGQ67i77MA",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "trunk",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Overhead Arch Rocks",
            "video": "https://youtube.com/shorts/PozR_Q8bXFA",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "trunk",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
        {
            "name": "Press Up into Superman",
            "video": "https://youtube.com/shorts/QggzomrMNy4",
            "rationale": "",
            "variations": [],
            "synergist": [],
            "traits": {
                "joint_action": "trunk",
            },
            "equipment": None,
            "eccentric_heavy": None,
            "weeks": None,
        },
    ],
}


# ═══════════════════════════════════════════════════════════════════════════
# REFERENCE STRUCTURES (not part of EXERCISE_DATABASE)
# ═══════════════════════════════════════════════════════════════════════════

HAMSTRING_CURL_CONTINUUM = {
    "fmax": [
        "Eccentric Slide Outs",
        "2 In and 1 Out",
        "Flywheel Hamstring Curls",
    ],
    "lme": [
        "Machine Hamstring Curls",
        "Slider Hamstring Curl",
        "Foam Roller Hamstring Curl",
        "Stability Ball Hamstring Curl",
    ],
    "motor_control": [
        "Prone Banded Hamstring Curls",
        "Band Accelerated Hamstring Curls",
    ],
}
